export const sortedData = [
    { id: 1, name: "Konsta Dada", src: "./../music/1.mp3" },
    { id: 2, name: "Men o'zimni sevaman", src: "./../music/2.m4a" },
    { id: 3, name: "Oqqan daryo", src: "./../music/3.mp3" },
    { id: 4, name: "Malikam", src: "./../music/4.mp3" },
    { id: 5, name: "Sog`indim", src: "./../music/5.mp3" },
    { id: 6, name: "Yig'lamagin ho'pmi", src: "./../music/6.mp3" },
    { id: 7, name: "Jiyda guli", src: "./../music/7.mp3" },
    { id: 8, name: "Ustimdan kulma", src: "./../music/8.mp3" },
    { id: 9, name: "Erkak yig'lamasin", src: "./../music/9.mp3" },
    { id: 10, name: "Kutyapman", src: "./../music/10.mp3" },
    { id: 11, name: "Besh O’g’il", src: "./../music/11.mp3" },
    { id: 12, name: "Konsta - Biz yo'q joyda", src: "./../music/12.mp3" },
    { id: 13, name: "Konsta - Dada", src: "./../music/13.mp3" },
    { id: 14, name: "Konsta - Havo", src: "./../music/14.mp3" },
    { id: 15, name: "Konsta - Insonlar", src: "./../music/15.mp3" },
    { id: 16, name: "Konsta - Jonga tegdi", src: "./../music/16.mp3" },
    { id: 17, name: "Konsta - Maska", src: "./../music/17.mp3" },
    { id: 18, name: "Konsta - Odamlar ucha olar", src: "./../music/18.mp3" },
    { id: 19, name: "Konsta - Qahramonlar", src: "./../music/19.mp3" },
    { id: 20, name: "KONSTA - SARIQ JILETKA", src: "./../music/20.mp3" },
    { id: 21, name: "Konsta - Yo'ldagi hayot", src: "./../music/21.mp3" },
    { id: 22, name: "KONSTA - O‘zbekistonlik", src: "./../music/22.mp3" },
    { id: 23, name: "Konsta – Gulim", src: "./../music/23.mp3" },
    { id: 24, name: "Konsta & Dilnoz - U haqida", src: "./../music/24.mp3" },
    { id: 25, name: "Konsta & Lola - Sog'indim", src: "./../music/25.mp3" },
    { id: 26, name: "Konsta & Ulug'bek - Poyga", src: "./../music/26.mp3" },
    { id: 27, name: "Siz_o'shamu", src: "./../music/27.mp3" },
    { id: 28, name: "Men-o-zimni-sevaman", src: "./../music/28.m4a" },
    { id: 29, name: "Nostalgia_pilot", src: "./../music/29.mp3" },
    { id: 30, name: "Mayli telba denglar", src: "./../music/30.mp3" },
    { id: 31, name: "18 000 Olam", src: "./../music/31.mp3" },
    { id: 32, name: "Seni_ko'rdim", src: "./../music/32.mp3" },
    { id: 33, name: "O'rik_gullaganda", src: "./../music/33.mp3" },
    { id: 34, name: "SHOHZAMON-MAYXONA", src: "./../music/34.mp3" },
    { id: 35, name: "SHOXRUX - OKEAN", src: "./../music/35.mp3" },
    { id: 36, name: "Shuhrat_Qayumov_Netay", src: "./../music/36.mp3" },
    { id: 37, name: "Vohid_Abdulhakim_Ming_yil", src: "./../music/37.mp3" },
    { id: 38, name: "Кетким_келиаябти_онажон", src: "./../music/38.mp3" },
    { id: 39, name: "Охунжон_Мадалиев_Курмасам_булмас", src: "./../music/39.mp3" },
    
];